"""
disease_info.py — Knowledge base for all 26 crop disease classes.
"""

DISEASE_INFO = {
    "Apple___Apple_scab": {
        "cause": "Fungal infection by Venturia inaequalis",
        "when": "Cool, wet spring weather",
        "who": "Apple trees, especially young leaves and fruit",
        "how": "Spreads via wind-dispersed spores from infected debris",
        "solution": "Apply fungicides (captan, myclobutanil); remove infected leaves",
        "prevention": "Plant resistant varieties; rake and destroy fallen leaves",
        "severity": "Moderate",
    },
    "Apple___Black_rot": {
        "cause": "Fungal pathogen Botryosphaeria obtusa",
        "when": "Warm, humid conditions during growing season",
        "who": "Apple fruit, leaves, and bark",
        "how": "Spreads through wounds and infected mummified fruit",
        "solution": "Prune infected branches; apply copper-based fungicides",
        "prevention": "Remove mummified fruit; maintain good orchard sanitation",
        "severity": "High",
    },
    "Apple___Cedar_apple_rust": {
        "cause": "Fungal pathogen Gymnosporangium juniperi-virginianae",
        "when": "Spring when cedar galls release spores",
        "who": "Apple leaves and fruit near cedar/juniper trees",
        "how": "Wind-dispersed spores from nearby cedar trees",
        "solution": "Apply fungicides at bud break; remove nearby cedars if possible",
        "prevention": "Plant rust-resistant apple varieties",
        "severity": "Moderate",
    },
    "Apple___healthy": {
        "cause": "No disease detected",
        "when": "N/A",
        "who": "Apple crop is in good condition",
        "how": "Good agricultural practices maintained",
        "solution": "Continue current crop management",
        "prevention": "Maintain regular monitoring and sanitation",
        "severity": "None",
    },
    "Blueberry___healthy": {
        "cause": "No disease detected",
        "when": "N/A",
        "who": "Blueberry crop is in good condition",
        "how": "Good agricultural practices maintained",
        "solution": "Continue current crop management",
        "prevention": "Maintain soil pH and proper irrigation",
        "severity": "None",
    },
    "Cherry_(including_sour)___Powdery_mildew": {
        "cause": "Fungal pathogen Podosphaera clandestina",
        "when": "Warm dry days with cool humid nights",
        "who": "Cherry leaves, shoots, and fruit",
        "how": "Wind-dispersed spores; thrives in shaded canopy",
        "solution": "Apply sulfur or potassium bicarbonate fungicides",
        "prevention": "Prune for airflow; avoid excess nitrogen fertilization",
        "severity": "Moderate",
    },
    "Cherry_(including_sour)___healthy": {
        "cause": "No disease detected",
        "when": "N/A",
        "who": "Cherry crop is in good condition",
        "how": "Good agricultural practices maintained",
        "solution": "Continue current crop management",
        "prevention": "Regular pruning and monitoring",
        "severity": "None",
    },
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": {
        "cause": "Fungal pathogen Cercospora zeae-maydis",
        "when": "Warm humid conditions with heavy dew",
        "who": "Maize leaves, reducing photosynthesis",
        "how": "Spreads via wind and rain splash from infected residue",
        "solution": "Apply foliar fungicides; use resistant hybrids",
        "prevention": "Crop rotation; tillage to reduce infected residue",
        "severity": "High",
    },
    "Corn_(maize)___Common_rust_": {
        "cause": "Fungal pathogen Puccinia sorghi",
        "when": "Cool temperatures with high humidity",
        "who": "Maize leaves causing yield loss",
        "how": "Wind-dispersed urediniospores from infected plants",
        "solution": "Apply fungicides early; plant resistant varieties",
        "prevention": "Use certified rust-resistant seed",
        "severity": "Moderate",
    },
    "Corn_(maize)___Northern_Leaf_Blight": {
        "cause": "Fungal pathogen Exserohilum turcicum",
        "when": "Moderate temperatures with wet weather",
        "who": "Maize upper leaves reducing grain fill",
        "how": "Wind and rain dispersal of conidia",
        "solution": "Fungicide application at tasseling; resistant hybrids",
        "prevention": "Crop rotation and residue management",
        "severity": "High",
    },
    "Corn_(maize)___healthy": {
        "cause": "No disease detected",
        "when": "N/A",
        "who": "Maize crop is in good condition",
        "how": "Good agricultural practices maintained",
        "solution": "Continue current crop management",
        "prevention": "Monitor regularly for early disease signs",
        "severity": "None",
    },
    "Grape___Black_rot": {
        "cause": "Fungal pathogen Guignardia bidwellii",
        "when": "Warm wet weather during growing season",
        "who": "Grape berries, leaves, and shoots",
        "how": "Spores released from overwintered mummified berries",
        "solution": "Apply fungicides from bud break; remove mummies",
        "prevention": "Good canopy management and sanitation",
        "severity": "High",
    },
    "Grape___Esca_(Black_Measles)": {
        "cause": "Complex of wood-rotting fungi (Phaeomoniella, Phaeoacremonium)",
        "when": "Hot dry summers following wet winters",
        "who": "Mature grapevines, causing internal wood decay",
        "how": "Enters through pruning wounds",
        "solution": "No cure; remove and destroy infected vines",
        "prevention": "Protect pruning wounds with fungicide paste; prune in dry weather",
        "severity": "Critical",
    },
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": {
        "cause": "Fungal pathogen Pseudocercospora vitis",
        "when": "Warm humid late-season conditions",
        "who": "Grape leaves causing premature defoliation",
        "how": "Spreads via rain splash and wind",
        "solution": "Apply copper-based fungicides",
        "prevention": "Improve air circulation; avoid overhead irrigation",
        "severity": "Moderate",
    },
    "Grape___healthy": {
        "cause": "No disease detected",
        "when": "N/A",
        "who": "Grape crop is in good condition",
        "how": "Good agricultural practices maintained",
        "solution": "Continue current crop management",
        "prevention": "Regular canopy management and monitoring",
        "severity": "None",
    },
    "Orange___Haunglongbing_(Citrus_greening)": {
        "cause": "Bacterial pathogen Candidatus Liberibacter asiaticus",
        "when": "Year-round; spread by Asian citrus psyllid insect",
        "who": "All citrus crops; no known cure",
        "how": "Transmitted by Asian citrus psyllid feeding",
        "solution": "Remove and destroy infected trees immediately",
        "prevention": "Control psyllid populations; use certified disease-free nursery stock",
        "severity": "Critical",
    },
    "Peach___Bacterial_spot": {
        "cause": "Bacterium Xanthomonas arboricola pv. pruni",
        "when": "Warm wet spring and summer",
        "who": "Peach leaves, fruit, and twigs",
        "how": "Spreads via rain splash and wind-driven rain",
        "solution": "Apply copper bactericides; remove infected tissue",
        "prevention": "Plant resistant varieties; avoid overhead irrigation",
        "severity": "Moderate",
    },
    "Peach___healthy": {
        "cause": "No disease detected",
        "when": "N/A",
        "who": "Peach crop is in good condition",
        "how": "Good agricultural practices maintained",
        "solution": "Continue current crop management",
        "prevention": "Regular pruning and monitoring",
        "severity": "None",
    },
    "Pepper,_bell___Bacterial_spot": {
        "cause": "Bacterium Xanthomonas campestris pv. vesicatoria",
        "when": "Warm wet conditions",
        "who": "Bell pepper leaves and fruit",
        "how": "Spreads via rain splash, contaminated tools, and seed",
        "solution": "Apply copper bactericides; remove infected plants",
        "prevention": "Use certified disease-free seed; crop rotation",
        "severity": "Moderate",
    },
    "Pepper,_bell___healthy": {
        "cause": "No disease detected",
        "when": "N/A",
        "who": "Bell pepper crop is in good condition",
        "how": "Good agricultural practices maintained",
        "solution": "Continue current crop management",
        "prevention": "Maintain proper spacing and irrigation",
        "severity": "None",
    },
    "Potato___Early_blight": {
        "cause": "Fungal pathogen Alternaria solani",
        "when": "Warm humid conditions; older plants more susceptible",
        "who": "Potato leaves starting from lower canopy",
        "how": "Spreads through infected soil and plant debris",
        "solution": "Apply fungicides (chlorothalonil, mancozeb); remove infected leaves",
        "prevention": "Crop rotation; proper field sanitation",
        "severity": "Moderate",
    },
    "Potato___Late_blight": {
        "cause": "Oomycete pathogen Phytophthora infestans",
        "when": "Cool wet weather (10-20°C with high humidity)",
        "who": "Potato leaves, stems, and tubers",
        "how": "Spreads rapidly by wind and water droplets",
        "solution": "Apply systemic fungicides immediately; destroy infected plants",
        "prevention": "Use certified seeds; avoid overhead irrigation; monitor forecasts",
        "severity": "Critical",
    },
    "Potato___healthy": {
        "cause": "No disease detected",
        "when": "N/A",
        "who": "Potato crop is in good condition",
        "how": "Good agricultural practices maintained",
        "solution": "Continue current crop management",
        "prevention": "Use certified seed potatoes; monitor regularly",
        "severity": "None",
    },
    "Raspberry___healthy": {
        "cause": "No disease detected",
        "when": "N/A",
        "who": "Raspberry crop is in good condition",
        "how": "Good agricultural practices maintained",
        "solution": "Continue current crop management",
        "prevention": "Prune old canes; maintain good air circulation",
        "severity": "None",
    },
    "Soybean___healthy": {
        "cause": "No disease detected",
        "when": "N/A",
        "who": "Soybean crop is in good condition",
        "how": "Good agricultural practices maintained",
        "solution": "Continue current crop management",
        "prevention": "Crop rotation and regular scouting",
        "severity": "None",
    },
    "Squash___Powdery_mildew": {
        "cause": "Fungal pathogens Podosphaera xanthii / Erysiphe cichoracearum",
        "when": "Warm dry days with cool nights; high humidity",
        "who": "Squash and cucurbit leaves",
        "how": "Wind-dispersed spores; does not require wet leaves",
        "solution": "Apply sulfur, neem oil, or potassium bicarbonate",
        "prevention": "Plant resistant varieties; ensure good air circulation",
        "severity": "Moderate",
    },
    "Strawberry___Leaf_scorch": {
        "cause": "Fungal pathogen Diplocarpon earlianum",
        "when": "Warm humid weather, especially during rainy seasons",
        "who": "Strawberry leaves, petioles, and runners",
        "how": "Spreads via rain splash from infected plant debris; overwinters in old leaves",
        "solution": "Apply fungicides (captan, thiram); remove and destroy infected leaves",
        "prevention": "Use resistant varieties; ensure good air circulation; avoid overhead irrigation; remove old leaf debris",
        "severity": "Moderate",
    },
    "Strawberry___healthy": {
        "cause": "No disease detected",
        "when": "N/A",
        "who": "Strawberry crop is in good condition",
        "how": "Good agricultural practices maintained",
        "solution": "Continue current crop management",
        "prevention": "Maintain proper spacing, mulching, and regular monitoring",
        "severity": "None",
    },
    "Tomato___Bacterial_spot": {
        "cause": "Bacterium Xanthomonas campestris pv. vesicatoria",
        "when": "Warm wet conditions (24-30°C); frequent rainfall or overhead irrigation",
        "who": "Tomato leaves, stems, and fruit; causes yield loss and fruit blemishes",
        "how": "Spreads via rain splash, contaminated seed, infected transplants, and tools",
        "solution": "Apply copper-based bactericides; remove severely infected plants; use streptomycin sprays early",
        "prevention": "Use certified disease-free seed; crop rotation (2-3 years); avoid overhead irrigation; sanitize tools",
        "severity": "High",
    },
    "Rice___Bacterial_leaf_blight": {
        "cause": "Bacterium Xanthomonas oryzae pv. oryzae",
        "when": "Warm humid conditions; monsoon/rainy season; flooded fields",
        "who": "Rice leaves, causing wilting and yellowing from leaf tips",
        "how": "Spreads through irrigation water, rain splash, wind, and infected seed",
        "solution": "Drain fields to reduce humidity; apply copper bactericides; remove infected plants",
        "prevention": "Use resistant varieties (e.g., IRBB lines); balanced fertilization (avoid excess nitrogen); use clean seed",
        "severity": "High",
    },
    "Rice___Brown_spot": {
        "cause": "Fungal pathogen Bipolaris oryzae (Cochliobolus miyabeanus)",
        "when": "Nutrient-deficient soils; drought stress followed by humidity",
        "who": "Rice leaves, sheaths, and grains; causes poor grain filling",
        "how": "Spreads via wind-borne conidia and infected seed",
        "solution": "Apply foliar fungicides (mancozeb, propiconazole); improve soil fertility with potassium and silicon",
        "prevention": "Use certified healthy seed; balanced fertilization; maintain proper water management; seed treatment with fungicides",
        "severity": "Moderate",
    },
    "Rice___Leaf_smut": {
        "cause": "Fungal pathogen Entyloma oryzae",
        "when": "Cool temperatures with high humidity; late growing season",
        "who": "Rice leaves, forming small black spots that reduce photosynthesis",
        "how": "Spreads via wind-dispersed spores; survives in crop residue",
        "solution": "Apply fungicides (propiconazole, carbendazim) at early symptoms; remove infected leaves",
        "prevention": "Use resistant varieties; proper field sanitation; balanced nitrogen fertilization; crop rotation",
        "severity": "Low",
    },
    "Wheat___Rust": {
        "cause": "Fungal pathogen Puccinia species (P. triticina for leaf rust, P. graminis for stem rust)",
        "when": "Cool to warm humid conditions (15-25°C); spring and early summer",
        "who": "Wheat leaves and stems; causes significant yield loss worldwide",
        "how": "Wind-dispersed urediniospores can travel hundreds of kilometers; rapid epidemic spread",
        "solution": "Apply fungicides (triazoles, strobilurins) at first sign; use resistant varieties",
        "prevention": "Plant rust-resistant cultivars; early planting; monitor weather forecasts; remove volunteer wheat",
        "severity": "High",
    },
    "Wheat___Powdery_mildew": {
        "cause": "Fungal pathogen Blumeria graminis f. sp. tritici",
        "when": "Cool humid conditions (15-22°C); dense canopy with poor air circulation",
        "who": "Wheat leaves, stems, and heads; reduces grain quality and yield",
        "how": "Wind-dispersed conidia; thrives in dense, heavily fertilized crops",
        "solution": "Apply fungicides (triadimefon, propiconazole, sulfur); reduce nitrogen application",
        "prevention": "Use resistant varieties; avoid excessive nitrogen; ensure proper plant spacing; early sowing",
        "severity": "Moderate",
    },
    "Wheat___healthy": {
        "cause": "No disease detected",
        "when": "N/A",
        "who": "Wheat crop is in good condition",
        "how": "Good agricultural practices maintained",
        "solution": "Continue current crop management",
        "prevention": "Regular scouting; balanced fertilization; crop rotation",
        "severity": "None",
    },
}

UNKNOWN_INFO = {
    "cause": "Unknown — image may be unclear or class not in training set",
    "when": "Unknown",
    "who": "Unknown",
    "how": "Unknown",
    "solution": "Consult a local agronomist for expert diagnosis",
    "prevention": "Regular crop monitoring and field scouting",
    "severity": "Unknown",
}


def get_info(disease_name: str) -> dict:
    return DISEASE_INFO.get(disease_name, UNKNOWN_INFO)
